# Generated by Django 5.1.2 on 2024-10-25 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='title',
            new_name='task',
        ),
        migrations.AlterField(
            model_name='task',
            name='published_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 10, 25, 18, 27, 42, 827724, tzinfo=datetime.timezone.utc)),
        ),
    ]
