# Generated by Django 5.1.2 on 2024-10-26 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_title_content_task_alter_task_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='published_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 10, 26, 17, 35, 30, 646787, tzinfo=datetime.timezone.utc)),
        ),
    ]
