# Generated by Django 5.1.2 on 2024-10-26 19:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_task_is_completed_alter_task_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
