# Generated by Django 5.1.2 on 2024-10-26 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_task_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='time',
            field=models.TimeField(default=datetime.time(19, 43, 26, 8853)),
        ),
    ]
