# Generated by Django 5.1.2 on 2024-10-27 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_task_description_delete_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 27, 17, 45, 12, 494253, tzinfo=datetime.timezone.utc)),
        ),
    ]
